### ISSUE TITLE
Add theme by to the footer of the docs

### ISSUE THREAD

**Issue by mohammedzamakhan** [mohammedzamakhan/ngx-loadable#19]
Add "Theme by @angular-extensions/elements" to the footer of the Docs website, along with "Made with ❤️ by @mohammedzamakhan" and link the @angular-extensions/elements to https://angular-extensions.github.io/elements

**Comment by m-aditya** [comment]
I could do that, could you assign it to me?

**Comment by mohammedzamakhan** [comment]
Thanks @m-aditya for taking this up 👍
