### ISSUE TITLE
Cannot find module 'src/app/product/product.module'

### ISSUE THREAD

**Issue by bjornharvold** [mohammedzamakhan/ngx-loadable#2]
Hi @mohammedzamakhan!

Thank you for writing this. Very handy indeed :-)

```
Angular CLI: 7.3.6
Node: 11.12.0
OS: darwin x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, elements
... forms, http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.6
@angular-devkit/build-angular      0.13.6
@angular-devkit/build-ng-packagr   0.13.6
@angular-devkit/build-optimizer    0.13.6
@angular-devkit/build-webpack      0.13.6
@angular-devkit/core               7.3.6
@angular-devkit/schematics         7.3.6
@angular/cdk                       7.3.5
@angular/cli                       7.3.6
@angular/flex-layout               7.0.0-beta.24
@angular/material                  7.3.5
@angular/pwa                       0.13.6
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.6
@schematics/angular                7.3.6
@schematics/update                 0.13.6
ng-packagr                         4.7.1
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0
```

Here's my module:

```
import {NgModule} from '@angular/core';
import {LandingComponent} from './landing/landing.component';
import {SharedModule} from '../shared/shared.module';

@NgModule({
  declarations: [LandingComponent],
  bootstrap: [LandingComponent],
  imports: [
    SharedModule
  ]
})
export class ProductModule { }

```

I followed your instructions. I registered a lazyModule in my project under options:

```
"lazyModules": [
  "projects/booking-engine/src/app/product/product.module"
]
```

I loaded the module like so:

```
LoadableModule.forRoot({
      appDir: 'src/app/',
      fileMappings: {
        product: 'src/app/product/product.module#ProductModule'
      }
    })
```

I tried to load the module using your directive and your service but both return an error.
`Cannot find module 'src/app/product/product.module'`

FYI My project is a web component using Angular Elements. 

Please let me know your thoughts.

**Comment by mohammedzamakhan** [comment]
I assume your module configuration should be 

LoadableModule.forRoot({
      appDir: 'projects/booking-engine/src/app/',
    })

**Comment by bjornharvold** [comment]
Hi @mohammedzamakhan 

I made the change and I also tried no forRoot configuration at all. Same error.

**Comment by mohammedzamakhan** [comment]
Did you stop your serve command and restart `ng serve`/ serve command?

**Comment by bjornharvold** [comment]
Yes, I did now. Still the same issue. Wondering if normal paths don't work if it's a web component with a shadow dom.

**Comment by mohammedzamakhan** [comment]
Can you create a sample project with Angular elements with this issue, maybe it could be Angular Elements issue, but I want to take a loot at it.

**Comment by bjornharvold** [comment]
[AngularElements.zip](https://github.com/mohammedzamakhan/ngx-loadable/files/3001654/AngularElements.zip)

I got it to work as a web component with a default project setup where everything is under src. But, when I moved the project into projects folder, mono repo style, it stopped working.

Thoughts?

**Comment by mohammedzamakhan** [comment]
You don't need 
```
fileMappings: {
        'lazy-module': 'src/app/lazy-module/lazy-module.module#LazyModuleModule'
      }
```

**Comment by bjornharvold** [comment]
Does the sample I attached work for you if you remove fileMappings?

**Comment by mohammedzamakhan** [comment]
Yeah it works for me

**Comment by bjornharvold** [comment]
Thank you @mohammedzamakhan! Works like a charm :-)
