### ISSUE TITLE
Add example for passing data (inputs and outputs) to the components

### ISSUE THREAD

**Issue by mohammedzamakhan** [mohammedzamakhan/ngx-loadable#21]
Add example for passing data to lazy loaded component.

We had this example in version-2 docs (which is not used currently). 

You need to use the `init` output to get the instance of the component and pass the inputs and outputs to the component.

https://github.com/mohammedzamakhan/ngx-loadable/blob/version-2/projects/demo/src/app/home/home.component.html#L85

**Comment by ReevMich** [comment]
I can take this up, if no one else if interested?

**Comment by mohammedzamakhan** [comment]
Cool!
