### ISSUE TITLE
Lazily loading module doesn't load up module specific configuration

### ISSUE THREAD

**Issue by bjornharvold** [mohammedzamakhan/ngx-loadable#3]
Here's my lazy module:

```
export function createTranslateLoader(http: HttpClient) {
  console.log('loading translate module');
  return new TranslateHttpLoader(http, './assets/i18n/product/', '.json?cb=' + new Date().getTime());
}

@NgModule({
  declarations: [
    LandingComponent
  ],
  bootstrap: [LandingComponent],
  entryComponents: [
    RoomModalComponent
  ],
  imports: [
    SharedModule,
    TranslateModule.forChild({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [HttpClient]
      },
      isolate: true,
      missingTranslationHandler: {provide: MissingTranslationHandler, useClass: MyMissingTranslationHandler}
    })
  ],
  exports: []
})
export class ProductModule { }
```

When the module is loaded, it correctly shows the bootstrapped component. However, it fails to load ngx-translate (https://medium.com/@TuiZ/how-to-split-your-i18n-file-per-lazy-loaded-module-with-ngx-translate-3caef57a738f) and it doesn't register the entryComponent so when I try to open the modal using Angular Material Dialog it gives me the error:

`VM1195 polyfills.js:2557 Uncaught Error: No component factory found for RoomModalComponent. Did you add it to @NgModule.entryComponents?`

Thoughts?

**Comment by mohammedzamakhan** [comment]
Hi @bjornharvold, were you able to solve this issue?

**Comment by bjornharvold** [comment]
Hi @mohammedzamakhan 

No, I have not been able to move any further with this. I don't know enough about the inner workings of loading a module to figure out why modules within the lazy module are not instantiating the way they normally do. 

Any help is appreciated!

**Comment by mohammedzamakhan** [comment]
@bjornharvold I was able to use ngx-translate and also use entryComponents without any issue https://github.com/mohammedzamakhan/issue-ngx-loadable

**Comment by bjornharvold** [comment]
Thank you @mohammedzamakhan. Will take a look at what you did.
