### ISSUE TITLE
Passing data to lazily loaded component 

### ISSUE THREAD

**Issue by ahmetuysal** [mohammedzamakhan/ngx-loadable#4]
Hi @mohammedzamakhan, thanks for the awesome work!

I want to pass data to the lazily loaded component from the parent component. 
Currently, I am using a service to share the data to the lazily loaded component as a workaround. 

Is it possible to accomplish this with a simple mechanism like `@Input` decorator?

Thanks

**Comment by Tibfib** [comment]
I'm also interested to hear the answer. This would be a huge help to our project.

**Comment by mohammedzamakhan** [comment]
@ahmetuysal @Tibfib update the version to 1.1.0. Added Input and Output support, check the demo at https://mohammedzamakhan.github.io/ngx-loadable/ and the code https://github.com/mohammedzamakhan/ngx-loadable/blob/master/projects/demo/src/app/app.component.html#L81
